name: 'Bikeclub FAQs'
description: 'Provides FAQs content type to display information in a collapsible question-and-answer format.'
type: 'Content type'
recipes:
  - bikeclub_content_type_base
install:
  # Contrib.
  - faqfield
config:
  strict: false
  actions:
    user.role.site_admin:
      createIfNotExists:
        label: 'Site administrator'
      grantPermissions:
        - 'create faqs content'
        - 'delete any faqs content'
        - 'edit any faqs content'
        - 'use text format basic_html'
        - 'use text format summary_fields'
