name: 'Bikeclub FAQs'
description: 'Provides FAQs content type to display information in a collapsible question-and-answer format.'
type: 'Content type'
recipes:
  - bikeclub_content_type_base
install:
  - layout_builder
  - layout_discovery
  - menu_ui
  # Contrib.
  - faqfield
  - scheduler  
config:
  strict: false
  import:
    scheduler: '*'
  actions:
    scheduler.settings:
      simple_config_update:
        allow_date_only: true
        default_time: '01:00:00'
        hide_seconds: true
        log: false
    user.role.site_admin:
      createIfNotExists:
        label: 'Site administrator'
      grantPermissions:
        - 'create faqs content'
        - 'delete any faqs content'
        - 'edit any faqs content'
        - 'use text format basic_html'
        - 'use text format summary_fields'
